#!/usr/bin/env python3
"""Generate each task's docker-compose.yaml from the central service catalog.

A task declares its services in task.toml:

    [metadata.services]
    backend = "postgres"
    storage = "minio"

...and this generator assembles environment/providers/<p>/service.yaml fragments
into tasks/<task>/environment/docker-compose.yaml -- the same "central source ->
generated per-task copy" model as sync_verifier.py for the grader files.

Pure stdlib -- runs on the system python3 (no venv, no pyyaml needed).

    python3 environment/compose.py --check              # compare generated vs current (all tasks)
    python3 environment/compose.py --task seat-allocation-map   # print generated compose
    python3 environment/compose.py --write --task <t>   # write it (copies generic seeds/assets)
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path

ENV = Path(__file__).resolve().parent
REPO = ENV.parent
REGISTRY = json.loads((ENV / "registry.json").read_text())
# order services are emitted in, to match the existing hand-written composes
SLOT_ORDER = ["backend", "db", "auth", "email", "storage", "payments"]

BANNER = (
    "# GENERATED by environment/compose.py from the central service catalog.\n"
    "# Do NOT edit by hand -- edit environment/providers/<provider>/ and regenerate.\n"
    "# Task-specific seed (pocketbase-init.sh, keycloak-realm.json) stays in this folder.\n"
)
MAIN_BLOCK = (
    "  # Harbor's agent container. Ports only -- Harbor merges this file LAST and\n"
    "  # controls image/build/env. Never add image/command/profiles here.\n"
    "  main:\n"
    "    ports:\n"
    '      - "4173:4173"\n'
)


def task_services(task: str) -> dict[str, str]:
    """Parse [metadata.services] from a task.toml (regex -- no tomllib needed)."""
    toml = (REPO / "tasks" / task / "task.toml").read_text()
    m = re.search(r"\[metadata\.services\](.*?)(?:\n\[|\Z)", toml, re.S)
    if not m:
        return {}
    out = {}
    for line in m.group(1).splitlines():
        kv = re.match(r'\s*([A-Za-z0-9_]+)\s*=\s*"([^"]+)"', line)
        if kv:
            out[kv.group(1)] = kv.group(2)
    return out


def ordered_providers(services: dict[str, str]) -> list[str]:
    picked = []
    for slot in SLOT_ORDER:
        if slot in services:
            picked.append(services[slot])
    # any slot not in SLOT_ORDER, appended stably
    for slot, prov in services.items():
        if slot not in SLOT_ORDER:
            picked.append(prov)
    return picked


def generate(task: str) -> str:
    services = task_services(task)
    providers = ordered_providers(services)
    parts = [BANNER, "services:\n"]
    for prov in providers:
        spec = REGISTRY["providers"].get(prov)
        if not spec:
            raise SystemExit(f"{task}: unknown provider {prov!r} (add it to registry.json)")
        parts.append((ENV / spec["fragment"]).read_text().rstrip("\n") + "\n\n")
    parts.append(MAIN_BLOCK)
    return "".join(parts)


def summarize(compose_text: str) -> dict[str, str | None]:
    """Structural fingerprint: service name -> image (or '<build>'). Comments and
    formatting are ignored; this is what must match for functional equivalence."""
    summary: dict[str, str | None] = {}
    name = None
    for line in compose_text.splitlines():
        m = re.match(r"^  ([A-Za-z0-9_-]+):\s*$", line)
        if m and not line.startswith("    "):
            name = m.group(1)
            summary.setdefault(name, None)
        elif name:
            im = re.match(r"\s*image:\s*(\S+)", line)
            if im:
                summary[name] = im.group(1)
            elif re.match(r"\s*build:", line):
                summary[name] = "<build>"
    summary.pop("services", None)
    return summary


def copy_assets(task: str) -> list[str]:
    """Copy generic seeds/assets (e.g. postgres-init.sh) into the task env dir."""
    env_dir = REPO / "tasks" / task / "environment"
    copied = []
    for prov in ordered_providers(task_services(task)):
        spec = REGISTRY["providers"].get(prov, {})
        if "generic_seed" in spec:
            src = ENV / spec["generic_seed"]["src"]
            dst = env_dir / spec["generic_seed"]["dst"]
            shutil.copy2(src, dst)
            # copy2 preserves the mode, so a source file that lost its exec bit
            # silently produces an unrunnable seed in every task generated from
            # it. postgres runs /docker-entrypoint-initdb.d/*.sh by EXECUTING it:
            #
            #   /docker-entrypoint-initdb.d/10-app-role.sh: /bin/sh: bad
            #   interpreter: Permission denied
            #
            # and it does not stop on that error. The database comes up healthy
            # without the unprivileged role, and every app that connects as
            # deku_app gets 28P01 -- which postgres reports identically for a
            # wrong password and a role that does not exist, so it reads as a
            # credentials bug in the app. Three tasks shipped this way and two of
            # them were the ones being debugged on 2026-08-10.
            dst.chmod(0o755)
            copied.append(dst.name)
        if "asset" in spec:
            src = ENV / spec["asset"]["src"]
            if src.exists():
                shutil.copytree(src, env_dir / spec["asset"]["dst"], dirs_exist_ok=True)
                copied.append(spec["asset"]["dst"] + "/")
    return copied


def cmd_check() -> int:
    tasks = sorted(p.parent.name for p in (REPO / "tasks").glob("*/task.toml"))
    ok = True
    for task in tasks:
        svc = task_services(task)
        if not svc:
            print(f"  {task:32s} no services (frontend-only) -- skip")
            continue
        current_path = REPO / "tasks" / task / "environment" / "docker-compose.yaml"
        cur = summarize(current_path.read_text()) if current_path.exists() else {}
        gen = summarize(generate(task))
        if cur == gen:
            print(f"✅ {task:32s} {list(gen)}  == current")
        else:
            ok = False
            print(f"❌ {task:32s} MISMATCH")
            print(f"     generated: {gen}")
            print(f"     current  : {cur}")
    return 0 if ok else 1


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--task", help="task name")
    ap.add_argument("--check", action="store_true", help="compare generated vs current for all tasks")
    ap.add_argument("--write", action="store_true", help="write compose + copy seeds into the task")
    args = ap.parse_args()

    if args.check:
        return cmd_check()
    if not args.task:
        ap.error("give --task <name> or --check")
    text = generate(args.task)
    if args.write:
        dst = REPO / "tasks" / args.task / "environment" / "docker-compose.yaml"
        dst.write_text(text)
        assets = copy_assets(args.task)
        print(f"wrote {dst.relative_to(REPO)}  (+ assets: {assets})")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
